# Generated by Django 5.2.3 on 2025-07-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='processed_file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zips/'),
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uploader.uploadedfile')),
            ],
        ),
    ]
